# Generated by Django 2.2.6 on 2021-02-12 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_auto_20210202_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposits',
            name='updated_at_str',
            field=models.CharField(blank=True, default='NA', max_length=200),
        ),
    ]
