# Generated by Django 2.2.6 on 2021-01-15 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='office_num',
            field=models.CharField(blank=True, default='NA', max_length=200),
        ),
    ]
