# Generated by Django 2.2.6 on 2021-01-15 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_office_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='company_name',
            field=models.CharField(blank=True, default='NA', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='office_num',
            field=models.CharField(blank=True, default='NA', max_length=200, null=True),
        ),
    ]
