# Generated by Django 2.2.6 on 2021-01-19 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customuser_cid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='cid',
            new_name='cid_id',
        ),
    ]
