# Generated by Django 2.2.6 on 2020-11-20 08:07

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_no', models.CharField(default='NA', max_length=20)),
                ('company_name', models.CharField(default='NA', max_length=20)),
                ('company_address', models.CharField(default='NA', max_length=200)),
                ('company_email', models.CharField(default='NA', max_length=100)),
                ('office_num', models.CharField(default='NA', max_length=100)),
                ('fax_number', models.CharField(default='NA', max_length=100)),
                ('status', models.CharField(choices=[('PAID', 'Paid'), ('PARTIAL', 'Partially Paid'), ('OUTSTANDING', 'Outstanding'), ('UNPAID', 'Unpaid')], default='UNPAID', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('due_at', models.DateTimeField(default=datetime.datetime(2020, 12, 20, 16, 7, 14, 996010))),
                ('domestic_flight', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('inbound_flight', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('outbound_flight', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('over_flight', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('other_flight', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('sub_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('surchage', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('invoice_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organisations.Organisation', to_field='cid')),
            ],
            options={
                'ordering': ['cid__name'],
            },
        ),
    ]
