# Generated by Django 2.2.6 on 2020-11-20 08:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='company_name',
            field=models.CharField(default='NA', max_length=200),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='due_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 20, 16, 29, 59, 482677)),
        ),
    ]
