# Generated by Django 2.2.6 on 2020-11-20 08:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_auto_20201120_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='company_address',
            field=models.CharField(default='NA', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='company_email',
            field=models.CharField(default='NA', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='company_name',
            field=models.CharField(default='NA', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='due_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 20, 16, 32, 7, 965430)),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='fax_number',
            field=models.CharField(default='NA', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='invoice_no',
            field=models.CharField(default='NA', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='office_num',
            field=models.CharField(default='NA', max_length=100, null=True),
        ),
    ]
