# Generated by Django 2.2.6 on 2020-11-21 15:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_auto_20201120_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='due_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 21, 23, 2, 3, 942525)),
        ),
    ]
