# Generated by Django 2.2.6 on 2020-11-21 15:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_auto_20201121_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='due_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 21, 23, 8, 45, 968339)),
        ),
    ]
