# Generated by Django 2.2.6 on 2020-11-22 18:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_auto_20201121_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='due_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 23, 2, 10, 12, 90103)),
        ),
    ]
