# Generated by Django 2.2.6 on 2020-11-23 04:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0007_auto_20201123_0210'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='total_flight',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='due_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 23, 12, 30, 53, 991078)),
        ),
    ]
