# Generated by Django 2.2.6 on 2020-11-24 14:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0008_auto_20201123_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='created_at_str',
            field=models.CharField(blank=True, default='NA', max_length=200),
        ),
        migrations.AddField(
            model_name='invoices',
            name='due_at_str',
            field=models.CharField(blank=True, default='NA', max_length=200),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='due_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 24, 22, 23, 2, 922954)),
        ),
    ]
