# Generated by Django 2.2.6 on 2020-11-24 14:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0009_auto_20201124_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='created_at_str',
            field=models.CharField(blank=True, default='NA', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='due_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 24, 22, 43, 38, 157057)),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='due_at_str',
            field=models.CharField(blank=True, default='NA', max_length=200, null=True),
        ),
    ]
