# Generated by Django 2.2.6 on 2020-11-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0010_auto_20201124_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
