# Generated by Django 2.2.6 on 2020-11-25 07:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0010_auto_20201124_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='due_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 25, 15, 0, 36, 40202)),
        ),
    ]
