# Generated by Django 2.2.6 on 2020-11-26 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0011_auto_20201125_2059'),
        ('invoice', '0011_auto_20201125_1500'),
    ]

    operations = [
    ]
