# Generated by Django 2.2.6 on 2020-12-20 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0011_auto_20201125_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='inv_period',
            field=models.CharField(blank=True, default='NA', max_length=20, null=True),
        ),
    ]
