# Generated by Django 2.2.6 on 2020-12-20 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0012_invoices_inv_period'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoices',
            options={'ordering': ['cid__name', 'inv_period']},
        ),
    ]
