# Generated by Django 2.2.6 on 2020-12-09 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0012_merge_20201127_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
