# Generated by Django 2.2.6 on 2021-01-24 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0014_auto_20201220_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
