# Generated by Django 2.2.6 on 2020-07-13 10:18

import core.helpers
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Callsign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('callsign', models.CharField(default='NA', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='NA', max_length=100)),
                ('rate_id', models.CharField(default='NA', max_length=100)),
                ('charge_rate', models.FloatField(blank=True, default=0)),
                ('charge_min', models.FloatField(blank=True, default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='NA', max_length=100)),
                ('lower_weight_limit', models.CharField(default='NA', max_length=100)),
                ('upper_weight_limit', models.CharField(default='NA', max_length=100)),
                ('rate', models.CharField(default='NA', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='NA', max_length=100)),
                ('description', models.CharField(default='NA', max_length=100)),
                ('rtid', models.CharField(default='NA', max_length=100)),
                ('distance', models.FloatField(blank=True, default=0)),
                ('total_distance', models.FloatField(blank=True, default=0)),
                ('flight_type', models.CharField(choices=[('D', 'Domestic'), ('I', 'International'), ('NA', 'Not Available')], default='NA', max_length=2)),
                ('category_type', models.CharField(choices=[('SC1', 'Sector 1'), ('SC2', 'Sector 2'), ('SC3', 'Sector 3'), ('NA', 'Not Available')], default='NA', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='NA', max_length=100)),
                ('data_type', models.CharField(choices=[('TFL', 'TFL'), ('VFR', 'VFR'), ('NA', 'Not Available')], default='NA', max_length=3)),
                ('document_url', models.FileField(blank=True, null=True, upload_to=core.helpers.PathAndRename('document'))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
