# Generated by Django 2.2 on 2020-04-11 03:22

import core.helpers
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('airports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organisations', '0002_auto_20200411_0322'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='NA', max_length=100)),
                ('lower_weight_limit', models.CharField(default='NA', max_length=100)),
                ('upper_weight_limit', models.CharField(default='NA', max_length=100)),
                ('rate', models.CharField(default='NA', max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='NA', max_length=100)),
                ('data_type', models.CharField(choices=[('TFL', 'TFL'), ('VFR', 'VFR'), ('NA', 'Not Available')], default='NA', max_length=3)),
                ('document_url', models.FileField(blank=True, null=True, upload_to=core.helpers.PathAndRename('document'))),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='NA', max_length=100)),
                ('description', models.CharField(default='NA', max_length=100)),
                ('distance', models.IntegerField(default=0)),
                ('category', models.CharField(choices=[('D', 'Domestic'), ('I', 'International'), ('NA', 'Not Available')], default='NA', max_length=2)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('location_departure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_departure', to='airports.Airport')),
                ('location_destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_destination', to='airports.Airport')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Callsign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('callsign', models.CharField(default='NA', max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('organisation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='callsign_organisation', to='organisations.Organisation')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
