# Generated by Django 2.2.6 on 2020-07-13 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operations', '0001_initial'),
        ('aircrafts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organisations', '0001_initial'),
        ('airports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='route',
            name='location_departure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_departure', to='airports.Airport'),
        ),
        migrations.AddField(
            model_name='route',
            name='location_destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_destination', to='airports.Airport'),
        ),
        migrations.AddField(
            model_name='charge',
            name='aircraft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charge_aircraft', to='aircrafts.Aircraft'),
        ),
        migrations.AddField(
            model_name='callsign',
            name='aircraft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='callsign', to='aircrafts.Aircraft'),
        ),
        migrations.AddField(
            model_name='callsign',
            name='cid',
            field=models.ForeignKey(limit_choices_to={'ORGANISATION_TYPE': 'AL'}, on_delete=django.db.models.deletion.CASCADE, related_name='callsign_organisation', to='organisations.Organisation'),
        ),
    ]
