# Generated by Django 2.2.6 on 2020-11-14 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operations', '0002_auto_20201112_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='modified_by',
            field=models.ForeignKey(limit_choices_to=models.Q(('user_type', 'OPS'), ('user_type', 'APT'), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_upload_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fpldata',
            name='modified_by',
            field=models.ForeignKey(limit_choices_to=models.Q(('user_type', 'OPS'), ('user_type', 'APT'), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fpl_data_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='approved_by',
            field=models.ForeignKey(limit_choices_to={'user_type': 'OPS'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_upload_approved_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='status',
            field=models.CharField(choices=[('FIL0', 'Draft'), ('FIL1', 'Processing'), ('FIL2', 'Checked'), ('FIL3', 'Approved'), ('FIL4', 'Cancel')], default='FIL0', max_length=4),
        ),
        migrations.AlterField(
            model_name='fpldata',
            name='approved_by',
            field=models.ForeignKey(limit_choices_to={'user_type': 'OPS'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fpl_data_approved_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fpldata',
            name='archived_by',
            field=models.ForeignKey(limit_choices_to=models.Q(('user_type', 'OPS'), ('user_type', 'APT'), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fpl_data_archived_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
