# Generated by Django 2.2.6 on 2020-08-26 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_auto_20200826_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
