# Generated by Django 2.2.6 on 2020-08-26 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_auto_20200826_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
