# Generated by Django 2.2.6 on 2020-07-20 10:21

import core.helpers
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20200720_1021'),
        ('organisations', '0002_auto_20200720_0855'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aircrafts', '0002_auto_20200713_1029'),
        ('operations', '0003_auto_20200713_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='NA', max_length=100)),
                ('data_type', models.CharField(choices=[('TFL', 'TFL'), ('VFR', 'VFR'), ('NA', 'Not Available')], default='NA', max_length=3)),
                ('data_file_link', models.FileField(blank=True, null=True, upload_to=core.helpers.PathAndRename('data_upload'))),
                ('flight_rule', models.CharField(choices=[('I', 'Instrument'), ('V', 'Visual')], default='I', max_length=1)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('touchdown', models.IntegerField(blank=True, default=0)),
                ('approval_permit_num', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_upload_aircraft', to='aircrafts.Aircraft')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='charge',
            name='charge_min',
        ),
        migrations.RemoveField(
            model_name='charge',
            name='name',
        ),
        migrations.RemoveField(
            model_name='charge',
            name='rate_id',
        ),
        migrations.AddField(
            model_name='charge',
            name='charge_minimum',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='charge',
            name='rate',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='charge_rate', to='operations.Rate'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='charge',
            name='charge_rate',
            field=models.FloatField(default=0),
        ),
        migrations.DeleteModel(
            name='Upload',
        ),
        migrations.AddField(
            model_name='fileupload',
            name='charge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_upload_charge', to='operations.Charge'),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='operator',
            field=models.ForeignKey(limit_choices_to={'organisation_type': 'AL'}, on_delete=django.db.models.deletion.CASCADE, related_name='file_upload_operator', to='organisations.Organisation'),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_upload_route', to='operations.Route'),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='uploaded_by',
            field=models.ForeignKey(limit_choices_to={'user_type': 'ST'}, on_delete=django.db.models.deletion.CASCADE, related_name='file_upload_uploaded_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
