# Generated by Django 2.2.6 on 2020-11-14 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_fpldata_fpl_date_ts'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='file_date_ts',
            field=models.DateTimeField(null=True),
        ),
    ]
