# Generated by Django 2.2.6 on 2020-08-27 03:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_auto_20200826_0321'),
    ]

    operations = [
        migrations.AddField(
            model_name='fpldata',
            name='fileupload',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_upload_id', to='operations.FileUpload'),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='uploaded_by',
            field=models.ForeignKey(limit_choices_to={'user_type': 'APT'}, on_delete=django.db.models.deletion.CASCADE, related_name='file_upload_uploaded_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
