# Generated by Django 2.2.6 on 2020-12-16 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_fileupload_file_date_ts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fpldata',
            options={'ordering': ['-error_remark']},
        ),
    ]
