# Generated by Django 2.2.6 on 2020-08-27 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_auto_20200827_0330'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='file_date',
            field=models.CharField(default='NA', max_length=8),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='total_data',
            field=models.IntegerField(default=0),
        ),
    ]
