# Generated by Django 2.2.6 on 2021-01-06 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0007_auto_20210106_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fpldata',
            name='aircraft_model',
            field=models.TextField(default='NA', max_length=10),
        ),
        migrations.AlterField(
            model_name='fpldata',
            name='dep',
            field=models.TextField(default='NA', max_length=10),
        ),
        migrations.AlterField(
            model_name='fpldata',
            name='dest',
            field=models.TextField(default='NA', max_length=10),
        ),
        migrations.AlterField(
            model_name='fpldata',
            name='fpl_no',
            field=models.TextField(default='NA', max_length=10),
        ),
        migrations.AlterField(
            model_name='fpldata',
            name='reason',
            field=models.TextField(default='NA', max_length=300),
        ),
        migrations.AlterField(
            model_name='fpldata',
            name='remark',
            field=models.TextField(default='NA', max_length=300),
        ),
        migrations.AlterField(
            model_name='fpldata',
            name='route',
            field=models.TextField(default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='fpldata',
            name='status',
            field=models.TextField(choices=[('FPL0', 'Draf'), ('FPL1', 'Processing'), ('FPL2', 'Checked'), ('FPL3', 'Archived'), ('FPL4', 'Approved')], default='FPL0', max_length=4),
        ),
    ]
