# Generated by Django 2.2.6 on 2021-01-21 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0008_auto_20210106_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fpldata',
            name='error_remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
