# Generated by Django 2.2.6 on 2020-09-02 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0008_auto_20200828_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='uploaded_by',
            field=models.ForeignKey(limit_choices_to=models.Q(('user_type', 'OPS'), ('user_type', 'APT'), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, related_name='file_upload_uploaded_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
