# Generated by Django 2.2.6 on 2020-09-02 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operations', '0009_auto_20200902_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='approved_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='approved_by',
            field=models.ForeignKey(limit_choices_to={'user_type': 'HOD'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_upload_approved_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='checked_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='checked_by',
            field=models.ForeignKey(limit_choices_to={'user_type': 'OPS'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_upload_checked_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fpldata',
            name='approved_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='fpldata',
            name='approved_by',
            field=models.ForeignKey(limit_choices_to={'user_type': 'HOD'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fpl_data_approved_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fpldata',
            name='archived_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='fpldata',
            name='archived_by',
            field=models.ForeignKey(limit_choices_to={'user_type': 'OPS'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fpl_data_archived_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fpldata',
            name='checked_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='fpldata',
            name='checked_by',
            field=models.ForeignKey(limit_choices_to={'user_type': 'OPS'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fpl_data_checked_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='status',
            field=models.CharField(choices=[('FIL0', 'Draf'), ('FIL1', 'Processing'), ('FIL2', 'Checked'), ('FIL3', 'Approved')], default='FIL0', max_length=4),
        ),
        migrations.AlterField(
            model_name='fpldata',
            name='status',
            field=models.CharField(choices=[('FPL0', 'Draf'), ('FPL1', 'Processing'), ('FPL2', 'Checked'), ('FPL3', 'Archived'), ('FPL4', 'Approved')], default='FPL0', max_length=4),
        ),
    ]
