# Generated by Django 2.2.6 on 2020-09-03 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0010_auto_20200902_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fpldata',
            name='cid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organisations.Organisation', to_field='cid'),
        ),
    ]
