# Generated by Django 2.2.6 on 2020-09-07 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operations', '0011_auto_20200903_0228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fpldata',
            options={},
        ),
        migrations.CreateModel(
            name='FpldataHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_changes', models.CharField(default='NA', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('master_data_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fpl_data_history_master_data_id', to='operations.Fpldata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fpl_data_history_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
