# Generated by Django 2.2.6 on 2021-01-23 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0011_auto_20210122_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='fpldata',
            name='computed',
            field=models.BooleanField(default=False),
        ),
    ]
