# Generated by Django 2.2.6 on 2021-02-11 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0013_fpldata_error_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fpldata',
            name='error_type',
            field=models.CharField(choices=[('FLIGHT', 'flight'), ('AIRLINE', 'airline')], default='NA', max_length=20),
        ),
    ]
