# Generated by Django 2.2.6 on 2021-01-15 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210113_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='company_name',
            field=models.CharField(blank=True, default='NA', max_length=200),
        ),
    ]
