# Generated by Django 2.2.6 on 2021-01-19 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210115_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='organisation',
            field=models.CharField(blank=True, default='NA', max_length=200, null=True),
        ),
    ]
