# Generated by Django 2.2.6 on 2021-01-19 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210120_0222'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cid',
            field=models.CharField(blank=True, default='NA', max_length=200, null=True),
        ),
    ]
