# Generated by Django 2.2.6 on 2020-11-24 15:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(blank=True, default='NA', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_at_str', models.CharField(blank=True, default='NA', max_length=200, null=True)),
                ('transaction', models.CharField(blank=True, default='NA', max_length=200)),
                ('transaction_number', models.CharField(blank=True, default='NA', max_length=200)),
                ('debit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('credit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('deposit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('outstanding', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organisations.Organisation', to_field='cid')),
            ],
            options={
                'ordering': ['cid__name'],
            },
        ),
    ]
