# Generated by Django 2.2.6 on 2020-11-24 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201124_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statements',
            name='deposit',
        ),
        migrations.RemoveField(
            model_name='statements',
            name='outstanding',
        ),
    ]
