# Generated by Django 2.2.6 on 2020-11-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201124_2352'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statements',
            options={'ordering': ['company_name']},
        ),
        migrations.AlterField(
            model_name='statements',
            name='transaction',
            field=models.CharField(choices=[('INVOICE', 'Invoice'), ('PAYMENT', 'Payment'), ('NA', 'Other')], default='NA', max_length=20),
        ),
    ]
