# Generated by Django 2.2.6 on 2020-11-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201125_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='statements',
            name='credit_account',
            field=models.CharField(default='NA', max_length=200),
        ),
        migrations.AddField(
            model_name='statements',
            name='credit_code',
            field=models.CharField(default='NA', max_length=200),
        ),
        migrations.AddField(
            model_name='statements',
            name='debit_account',
            field=models.CharField(default='NA', max_length=200),
        ),
        migrations.AddField(
            model_name='statements',
            name='debit_code',
            field=models.CharField(default='NA', max_length=200),
        ),
        migrations.AlterField(
            model_name='statements',
            name='transaction',
            field=models.CharField(choices=[('INVOICE', 'Invoice'), ('PAYMENT', 'Payment'), ('FOREX', 'Forex'), ('NA', 'Other')], default='NA', max_length=20),
        ),
    ]
