# Generated by Django 2.2.6 on 2020-11-25 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20201125_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statements',
            name='credit_account',
            field=models.CharField(blank=True, default='NA', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='statements',
            name='credit_code',
            field=models.CharField(blank=True, default='NA', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='statements',
            name='debit_account',
            field=models.CharField(blank=True, default='NA', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='statements',
            name='debit_code',
            field=models.CharField(blank=True, default='NA', max_length=200, null=True),
        ),
    ]
