# Generated by Django 2.2 on 2020-04-11 03:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0002_auto_20200411_0322'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('registration_num', models.CharField(default='NA', max_length=100)),
                ('model', models.CharField(default='NA', max_length=100)),
                ('manufacturer', models.CharField(default='NA', max_length=100)),
                ('description', models.CharField(default='NA', max_length=255)),
                ('mtow', models.IntegerField(default=0)),
                ('aircraft_type', models.CharField(choices=[('H', 'Choppper'), ('FW', 'Fixed Wing'), ('NA', 'Not Available')], default='NA', max_length=2)),
                ('aircraft_category', models.CharField(choices=[('L', 'Light'), ('M', 'Medium'), ('H', 'Heavy'), ('NA', 'Not Available')], default='NA', max_length=2)),
                ('rate', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aircraft_airline', to='organisations.Organisation')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
