# Generated by Django 2.2.6 on 2020-08-26 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircrafts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
