# Generated by Django 2.2.6 on 2020-07-13 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aircrafts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='manufacturer',
            field=models.ForeignKey(limit_choices_to={'organisation_type': 'MN'}, on_delete=django.db.models.deletion.CASCADE, related_name='aircraft_airline', to='organisations.Organisation'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='operator',
            field=models.ForeignKey(limit_choices_to={'organisation_type': 'AL'}, on_delete=django.db.models.deletion.CASCADE, related_name='aircraft_operator', to='organisations.Organisation'),
        ),
    ]
