# Generated by Django 2.2.6 on 2020-08-28 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aircrafts', '0002_auto_20200826_0401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='manufacturer',
            field=models.ForeignKey(blank=True, limit_choices_to={'organisation_type': 'MN'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aircraft_airline', to='organisations.Organisation'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='operator',
            field=models.ForeignKey(blank=True, limit_choices_to={'organisation_type': 'AL'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aircraft_operator', to='organisations.Organisation'),
        ),
    ]
