# Generated by Django 2.2.6 on 2021-01-22 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_note_note_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='cid',
            new_name='cid_id',
        ),
    ]
