# Generated by Django 2.2.6 on 2021-01-22 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispute', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispute',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('REJECTED', 'Rejected'), ('ACCEPTED', 'Accepted'), ('PROCESSED', 'Processed'), ('CLOSED', 'Closed')], default='OPEN', max_length=20),
        ),
    ]
