# Generated by Django 2.2.6 on 2021-01-22 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispute', '0002_dispute_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dispute',
            old_name='cid',
            new_name='cid_id',
        ),
    ]
