# Generated by Django 2.2.6 on 2021-01-22 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispute', '0003_auto_20210123_0121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dispute',
            old_name='cid_id',
            new_name='cid',
        ),
    ]
