# Generated by Django 2.2.6 on 2021-02-03 04:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispute', '0004_auto_20210123_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispute',
            name='arch_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='fpl_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
    ]
