# Generated by Django 2.2.6 on 2020-11-22 17:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('code', models.CharField(blank=True, default='NA', max_length=200)),
                ('payment_method', models.CharField(blank=True, default='NA', max_length=200)),
                ('remark', models.TextField(blank=True, null=True)),
                ('amount_receive', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('summary', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organisations.Organisation', to_field='cid')),
            ],
        ),
    ]
