# Generated by Django 2.2.6 on 2020-11-22 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='cid',
            field=models.ForeignKey(default='NA', on_delete=django.db.models.deletion.CASCADE, to='organisations.Organisation', to_field='cid'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='summary',
            field=models.TextField(blank=True, default='NA', null=True),
        ),
    ]
