# Generated by Django 2.2.6 on 2020-07-13 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='operator',
            field=models.ForeignKey(limit_choices_to={'organisation_type': 'AL'}, on_delete=django.db.models.deletion.CASCADE, related_name='reminder_operator', to='organisations.Organisation'),
        ),
    ]
