# Generated by Django 2.2.6 on 2020-11-22 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20201123_0156'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='online',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
