# Generated by Django 2.2.6 on 2020-07-20 10:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20200713_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('minimium', models.FloatField(default=0)),
                ('maximum', models.FloatField(default=0)),
                ('price_amount', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='uploaded_data',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='uploaded_data',
        ),
    ]
