# Generated by Django 2.2.6 on 2020-11-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payments_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
