# Generated by Django 2.2.6 on 2020-07-20 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_auto_20200720_1021'),
        ('payments', '0003_auto_20200720_1021'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rate',
        ),
        migrations.AddField(
            model_name='invoice',
            name='uploaded_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_uploaded_data', to='operations.FileUpload'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='uploaded_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipt_uploaded_data', to='operations.FileUpload'),
        ),
    ]
