# Generated by Django 2.2.6 on 2020-11-23 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_payments_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='status',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('UNAPPROVED', 'Unapproved')], default='UNAPPROVED', max_length=20),
        ),
    ]
