# Generated by Django 2.2.6 on 2020-11-23 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_payments_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='remark',
            field=models.TextField(blank=True, default='No remark for online transaction', null=True),
        ),
    ]
