# Generated by Django 2.2.6 on 2020-11-23 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_auto_20201123_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='approved',
            field=models.BooleanField(),
        ),
    ]
