# Generated by Django 2.2.6 on 2020-11-24 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_payments_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='cid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organisations.Organisation', to_field='cid'),
        ),
    ]
