# Generated by Django 2.2.6 on 2021-01-23 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_auto_20201124_0948'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payments',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='payments',
            name='company_id',
            field=models.CharField(blank=True, default='NA', max_length=200),
        ),
    ]
