# Generated by Django 2.2.6 on 2021-02-02 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_deposits'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='created_at_str',
            field=models.CharField(blank=True, default='NA', max_length=200),
        ),
    ]
