# Generated by Django 2.2.6 on 2021-02-02 08:22

import core.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_payments_created_at_str'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=core.helpers.PathAndRename('payment-attachment')),
        ),
    ]
