# Generated by Django 2.2.6 on 2021-01-19 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='pic_department',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='organisation',
            name='pic_email',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='organisation',
            name='pic_position',
            field=models.CharField(default='NA', max_length=100),
        ),
    ]
