# Generated by Django 2.2.6 on 2021-01-19 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0002_auto_20210119_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='cid_id',
            field=models.CharField(default='NA', max_length=100),
        ),
    ]
