# Generated by Django 2.2.6 on 2021-01-23 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0003_organisation_cid_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='cid',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True),
        ),
    ]
