# Generated by Django 2.2.6 on 2020-08-26 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
