# Generated by Django 2.2 on 2020-04-11 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organisation',
            options={'ordering': ['-created_date']},
        ),
        migrations.AddField(
            model_name='organisation',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='organisation',
            name='cid',
            field=models.CharField(default='NA', max_length=4),
        ),
        migrations.AddField(
            model_name='organisation',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='organisation',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='organisation',
            name='email',
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='fax_number',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='organisation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='mobile_num',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='organisation',
            name='office_num',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='organisation',
            name='organisation_type',
            field=models.CharField(choices=[('AL', 'Airline'), ('OT', 'Others')], default='OT', max_length=2),
        ),
        migrations.AddField(
            model_name='organisation',
            name='pic_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='organisation',
            name='pic_num',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='organisation',
            name='postcode',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='organisation',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
